/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WIndexRouteImport } from './routes/w.index'
import { Route as WNewRouteImport } from './routes/w.new'
import { Route as WWorkshopIdIndexRouteImport } from './routes/w.$workshopId.index'
import { Route as WWorkshopIdStageStageKeyRouteImport } from './routes/w.$workshopId.stage.$stageKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WIndexRoute = WIndexRouteImport.update({
  id: '/w/',
  path: '/w/',
  getParentRoute: () => rootRouteImport,
} as any)
const WNewRoute = WNewRouteImport.update({
  id: '/w/new',
  path: '/w/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkshopIdIndexRoute = WWorkshopIdIndexRouteImport.update({
  id: '/w/$workshopId/',
  path: '/w/$workshopId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkshopIdStageStageKeyRoute =
  WWorkshopIdStageStageKeyRouteImport.update({
    id: '/w/$workshopId/stage/$stageKey',
    path: '/w/$workshopId/stage/$stageKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/new': typeof WNewRoute
  '/w/': typeof WIndexRoute
  '/w/$workshopId/': typeof WWorkshopIdIndexRoute
  '/w/$workshopId/stage/$stageKey': typeof WWorkshopIdStageStageKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w/new': typeof WNewRoute
  '/w': typeof WIndexRoute
  '/w/$workshopId': typeof WWorkshopIdIndexRoute
  '/w/$workshopId/stage/$stageKey': typeof WWorkshopIdStageStageKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/new': typeof WNewRoute
  '/w/': typeof WIndexRoute
  '/w/$workshopId/': typeof WWorkshopIdIndexRoute
  '/w/$workshopId/stage/$stageKey': typeof WWorkshopIdStageStageKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/new'
    | '/w/'
    | '/w/$workshopId/'
    | '/w/$workshopId/stage/$stageKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/w/new' | '/w' | '/w/$workshopId' | '/w/$workshopId/stage/$stageKey'
  id:
    | '__root__'
    | '/'
    | '/w/new'
    | '/w/'
    | '/w/$workshopId/'
    | '/w/$workshopId/stage/$stageKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WNewRoute: typeof WNewRoute
  WIndexRoute: typeof WIndexRoute
  WWorkshopIdIndexRoute: typeof WWorkshopIdIndexRoute
  WWorkshopIdStageStageKeyRoute: typeof WWorkshopIdStageStageKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/': {
      id: '/w/'
      path: '/w'
      fullPath: '/w/'
      preLoaderRoute: typeof WIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/new': {
      id: '/w/new'
      path: '/w/new'
      fullPath: '/w/new'
      preLoaderRoute: typeof WNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workshopId/': {
      id: '/w/$workshopId/'
      path: '/w/$workshopId'
      fullPath: '/w/$workshopId/'
      preLoaderRoute: typeof WWorkshopIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workshopId/stage/$stageKey': {
      id: '/w/$workshopId/stage/$stageKey'
      path: '/w/$workshopId/stage/$stageKey'
      fullPath: '/w/$workshopId/stage/$stageKey'
      preLoaderRoute: typeof WWorkshopIdStageStageKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WNewRoute: WNewRoute,
  WIndexRoute: WIndexRoute,
  WWorkshopIdIndexRoute: WWorkshopIdIndexRoute,
  WWorkshopIdStageStageKeyRoute: WWorkshopIdStageStageKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
